name: Build and Release AIpexium IDE

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Windows x64 min
        run: npm run gulp -- vscode-win32-x64-min

      - name: Build Inno Updater
        run: npm run gulp -- vscode-win32-x64-inno-updater

      - name: Build User Setup
        run: npm run gulp -- vscode-win32-x64-user-setup

      - name: Build System Setup
        run: npm run gulp -- vscode-win32-x64-system-setup

      - name: Rename and collect setup files
        shell: pwsh
        run: |
          # Create output directory
          New-Item -ItemType Directory -Force -Path ./release-output
          
          # Copy and rename User Setup
          $userSetupPath = ".build/win32-x64/user-setup/SIIDSetup.exe"
          if (Test-Path $userSetupPath) {
            Copy-Item $userSetupPath -Destination "./release-output/SIIDUserSetup.exe"
            Write-Host "✓ User Setup copied and renamed"
          } else {
            Write-Error "User Setup not found at $userSetupPath"
            exit 1
          }
          
          # Copy and rename System Setup
          $systemSetupPath = ".build/win32-x64/system-setup/SIIDSetup.exe"
          if (Test-Path $systemSetupPath) {
            Copy-Item $systemSetupPath -Destination "./release-output/SIIDSystemSetup.exe"
            Write-Host "✓ System Setup copied and renamed"
          } else {
            Write-Error "System Setup not found at $systemSetupPath"
            exit 1
          }

      - name: Generate checksums
        shell: pwsh
        run: |
          cd release-output
          Get-FileHash -Algorithm SHA256 SIIDUserSetup.exe | Select-Object Hash | Out-File -FilePath SIIDUserSetup.exe.sha256
          Get-FileHash -Algorithm SHA256 SIIDSystemSetup.exe | Select-Object Hash | Out-File -FilePath SIIDSystemSetup.exe.sha256
          Write-Host "✓ Checksums generated"

      - name: Get version from tag
        id: get_version
        shell: bash
        run: |
          echo "version=$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: AIpexium IDE Release ${{ steps.get_version.outputs.version }}
          tag_name: release-${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: false
          body: |
            ## AIpexium IDE Installers
            
            **Build Date:** ${{ steps.get_version.outputs.version }}
            
            ### Downloads:
            - **SIIDUserSetup.exe** - User installation (installs for current user only)
            - **SIIDSystemSetup.exe** - System installation (installs for all users, requires admin)
            
            ### Checksums:
            Use the .sha256 files to verify your download integrity.
          files: |
            release-output/SIIDUserSetup.exe
            release-output/SIIDSystemSetup.exe
            release-output/SIIDUserSetup.exe.sha256
            release-output/SIIDSystemSetup.exe.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aipexium-ide-installers-${{ steps.get_version.outputs.version }}
          path: |
            release-output/SIIDUserSetup.exe
            release-output/SIIDSystemSetup.exe
